#!/bin/bash

## Description: Delete wordpress files and database completely, beware: removes untracked git files
## Usage: delete-wp
## Example: "ddev delete-wp"

# TODO: use same dialog as ddev delete, it's nicer

read -p "Are you sure to delete database and /wordpress/ directory? This can not be undone. [Type y if sure, n to abort]" -n 1 -r
echo    # (optional) move to a new line
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

# We use ddev exec here because its a host command, --path is needed as well for WP CLI
echo "Deleting database via WP CLI and deleting wordpress folder ..."
ddev exec "wp db clean --yes --path=${DDEV_DOCROOT} && rm -rf /var/www/html/wordpress/"