#!/bin/bash

## Description: Delete updraft backups on local instance
## Usage: delete-backups
## Example: "ddev delete-backups"

# TODO: USE DDEV_DOCROOT? (it's empty in web commands?)

# TODO: Prompt user if he/she really wants to delete the backup files?

UPDRAFT_FOLDER="/var/www/html/ddev-wordpress/wp-content/updraft"

if [ ! -d $UPDRAFT_FOLDER ]
then 
  echo "Updraft folder not found, aborting."
  exit 2;
fi

cd "$UPDRAFT_FOLDER"
if [ $? -ne 0 ]
then  
    echo "Could not change dir to updraft folder, aborting."
    exit 1
fi

echo "Reading nonce information from file (maybe) created at install-wp ..."
NONCE_FILE=/var/www/html/fresh_install_nonce.txt
if [[ -f "$NONCE_FILE" ]]
then
    source "$NONCE_FILE"
    echo "Nonce retrieved for fresh restore point: ${FRESH_INSTALL_NONCE}"
    echo "Deleting all .zip and .gz in ${UPDRAFT_FOLDER} (except fresh restore point))"
    
    find . -type f -name "*.zip" -a -not -name "*${FRESH_INSTALL_NONCE}*" -delete -print
    find . -type f -name "*.gz" -a -not -name "*${FRESH_INSTALL_NONCE}*" -delete -print

else
    echo "(No nonce restore point found)"
    echo "Deleting all .zip and .gz in ${UPDRAFT_FOLDER} (except fresh restore point))"
    find . -type f -name "*.gz" -o -name "*.zip" -o -name "log.*.txt" -delete -print
fi