#!/bin/bash

## Description: Install fresh wordpress with updraftplus
## Usage: install-wp
## Example: "ddev install-wp <de_DE>"

if [ -z "$1" ]
  then
    # if no locale is provided, ask user if he/she really wants to use en_US
    WP_LOCALE_DEFAULT="en_US"
    read -p "Okay to use locale en_US? [$WP_LOCALE_DEFAULT]: " WP_LOCALE_INPUT
    WP_LOCALE="${WP_LOCALE_INPUT:-$WP_LOCALE_DEFAULT}"
  else
    # if user provided a locale, just set it
    WP_LOCALE="${1}"
fi

# We use a subdirectory in DDEV container, see "docroot" in .ddev/config.yaml
mkdir -p /var/www/html/wordpress

# Working directory
cd /var/www/html/wordpress

echo "Installing fresh wordpress with ${WP_LOCALE} ..."
wp core download --locale=${WP_LOCALE}
wp config create --dbname=db --dbuser=db --dbpass=db --dbhost=db
wp core install --url=${DDEV_PRIMARY_URL} --title=FreshPlainWordpress --admin_user=admin --admin_email=admin@pullwp.nohost

# disable automatic updates for the local instance
wp config set AUTOMATIC_UPDATER_DISABLED true --raw

# set debug values for local development
# TODO: figure out if this slows down the restore process?
# wp config set WP_DEBUG true --raw
# wp config set WP_DEBUG_LOG true --raw
# wp config set WP_DEBUG_DISPLAY false --raw

# TODO: Cache it to avoid unnecessary data transfer?
echo "Downloading updraftplus plugin as zip (needed for premium addons)..."
wget https://updraftplus.com/wp-content/uploads/updraftplus.zip
echo "Installing and activating it..."
wp plugin install updraftplus.zip --activate
rm updraftplus.zip

wp user update admin --prompt=user_pass

echo "Fresh wordpress with updraftplus installed at ${DDEV_PRIMARY_URL} - nice!"
echo "Next step: Activate your updratfplus premium license / CLI and Migrator plugin here:"
echo "${DDEV_PRIMARY_URL}/wp-admin/options-general.php?page=updraftplus"
echo "(You can launch your website with ddev launch from commandline)"

echo "Do you want to create a local updraftplus backup to make resets easier after restore? (optional, recommened)"
echo "Please activate your updraftplus license before(!) running this backup!"
CREATE_LOCAL_BACKUP_DEFAULT="yes"
read -p "Create local backup now? (yes/no) [$CREATE_LOCAL_BACKUP_DEFAULT]: " CREATE_LOCAL_BACKUP_INPUT
CREATE_LOCAL_BACKUP="${CREATE_LOCAL_BACKUP_INPUT:-$CREATE_LOCAL_BACKUP_DEFAULT}"
#echo "Option chosen: ${CREATE_LOCAL_BACKUP}"
if [[ $CREATE_LOCAL_BACKUP != "yes" && $CREATE_LOCAL_BACKUP != "no"  ]]
  then
    echo "Please enter yes or no, aborting."
    exit 1
  fi

if [[ $CREATE_LOCAL_BACKUP == "yes" ]]
  then
    echo "Creating local backup ..."
    UPDRAFT_TERMINAL_OUTPUT=`wp updraftplus backup`
    # we strip identifier (nonce) for backup from string after last : character
    # (Output will be something like: Success ... identifier: a7cfeXXXXc281)
    UPDRAFT_NONCE=${UPDRAFT_TERMINAL_OUTPUT##*: }
    # TODO: Error handling - check if nonce contains numbers/characters? check format?
    echo "Saving this nonce/identifier in local file ..."
    echo 'FRESH_INSTALL_NONCE="'"$UPDRAFT_NONCE"'"' >> ../fresh_install_nonce.txt
    # source it later with
    # source ~/fresh_install_nonce.txt
fi