#!/bin/bash

## Description: Reset an installed wordpress
## Usage: ddev reset-wp
## Example: "ddev reset-wp"

# TODO: not completed yet, let updraftplus activated?

# delete all wp mysql tables with help of wp cli
ddev exec wp db clean --yes --path=${DDEV_DOCROOT}