#!/bin/bash

## Description: Reset local installation to the backup created on setup
## Usage: reset-wp
## Example: "ddev reset-wp"

cd ddev-wordpress/

echo "Reading nonce information from file (maybe) created at install-wp ..."
NONCE_FILE=/var/www/html/fresh_install_nonce.txt
if [[ -f "$NONCE_FILE" ]]
then
    source "$NONCE_FILE"
    
    echo "Setting current wordpress version to version of restore point (${WP_CORE_VERSION}) ..."
    #TODO: compare
    wp core update --version=${WP_CORE_VERSION} --force
    
    echo "Nonce retrieved for fresh restore point: ${FRESH_INSTALL_NONCE}"
    echo "Restoring the local site ..."
    
    wp updraftplus restore $FRESH_INSTALL_NONCE --migration=true
    echo "Delete -old/-directories created by updraftplus"
    find . -type d -name '*-old' -exec rm -r {} +

    echo "Reset to fresh installation complete."
    echo "[You can always open your website with 'ddev launch' from commandline]"
else
    echo "No nonce/restore point found, aborting."
fi