#!/bin/bash

## Description: Setup symlink for (child) theme
## Usage: setup-symlink
## Example: "ddev setup-symlink theme mychild-theme"
# run this after a successful restore by updraftplus migrator

if [ -z "$1" ]
  then
    echo "Please select 'theme' or 'plugin'"
    exit 1
  else
    ENTITY_FOLDER="${1}s"
fi

if [ -z "$2" ]
  then
    echo "No theme name provided"
    exit 1
  else
    THEME_PLUGIN_NAME=$2
fi

# check if child theme is a symlink or the directory of a restored backup
# if it is from a restored backup, we delete it & add a symlink
if [ ! -L "/var/www/html/wordpress/wp-content/${ENTITY_FOLDER}/${THEME_PLUGIN_NAME}" ]
  then 
    echo "Theme or Plugin is not a symlink, delete it, add symlink."
    rm -rfv /var/www/html/wordpress/wp-content/${ENTITY_FOLDER}/${THEME_PLUGIN_NAME}
    ln -sv /var/www/html/symlinked-${ENTITY_FOLDER}/${THEME_PLUGIN_NAME} /var/www/html/wordpress/wp-content/${ENTITY_FOLDER}/${THEME_PLUGIN_NAME}
  else 
    echo "Symlink for theme is correct."
fi